/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathu;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Papun Gandha
 */
public class EnterLogin extends javax.swing.JFrame {

    /**
     * Creates new form EnterLogin
     */
    String username;
    String thename;
    public EnterLogin() {
        initComponents();
        username = getNameof();
        thename = getname();
    }
    public  String getUserName()
    {
        
        //username=MUserid.getText();
        return username;
    }
    
    public String getthename()
    {
        return thename;
        //return "NAND";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MUserid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MUserPassword = new javax.swing.JPasswordField();
        MUserShowPassword = new javax.swing.JCheckBox();
        MUserLoginButton = new javax.swing.JButton();
        MBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("USER ID");

        MUserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUseridActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("PASSWORD");

        MUserShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MUserShowPassword.setForeground(new java.awt.Color(0, 102, 0));
        MUserShowPassword.setText("Show Password");
        MUserShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUserShowPasswordActionPerformed(evt);
            }
        });

        MUserLoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MUserLoginButton.setForeground(new java.awt.Color(0, 102, 102));
        MUserLoginButton.setText("LOG IN");
        MUserLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUserLoginButtonActionPerformed(evt);
            }
        });

        MBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MBack.setForeground(new java.awt.Color(0, 102, 102));
        MBack.setText("BACK");
        MBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MUserShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MUserLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(MBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(662, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MUserShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MUserLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MUseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MUseridActionPerformed

    private void MUserShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUserShowPasswordActionPerformed
        // TODO add your handling code here:
         if(MUserShowPassword.isSelected())
        {
            MUserPassword.setEchoChar((char)0);
        }
        else
        {
            MUserPassword.setEchoChar('*');
        }
         
    }//GEN-LAST:event_MUserShowPasswordActionPerformed
    public void close(){
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }
    static String userid;
    static String iname;
    private void MUserLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUserLoginButtonActionPerformed
        // TODO add your handling code here:
        Scanner filename;
        
        try
        {
            userid = MUserid.getText().concat(".txt");
            iname = MUserid.getText();
            String password = MUserPassword.getText();
            
            filename = new Scanner(new File(userid));
            String[] biodata = new String[6];
            
            while(filename.hasNext())
            {
                biodata[0]= filename.next();
                biodata[1] = filename.next();
                biodata[2] = filename.next();
                biodata[3] = filename.next();
                biodata[4] = filename.next();
                biodata[5] = filename.next();
            }
            if(password.equals(biodata[2]))
            {
                new SocioNet().setVisible(true);
                close();
            }
            else
            {
                //new WrongPassword().setVisible(true);
                JOptionPane.showMessageDialog(null,"Wrong Password","Error Message",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(Exception e)
        {
            //System.out.println("Can't Open");
             JOptionPane.showMessageDialog(null,"No such ID exists","Error Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_MUserLoginButtonActionPerformed
   public static String getNameof()
   {
       return userid;
   }
   public static String getname()
   {
       return iname;
   }
    private void MBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBackActionPerformed
        // TODO add your handling code here:
        new FirstPage().setVisible(true);
        close();
    }//GEN-LAST:event_MBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MBack;
    private javax.swing.JButton MUserLoginButton;
    private javax.swing.JPasswordField MUserPassword;
    private javax.swing.JCheckBox MUserShowPassword;
    private javax.swing.JTextField MUserid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
