/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathu;
import java.util.Scanner;
import java.util.*;
import java.io.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.WindowEvent;
/**
 *
 * @author Papun Gandha
 */
public class MathuraTudu extends javax.swing.JFrame {

    /**
     * Creates new form MathuraTudu
     */
    static MathuraTudu obj;
    public MathuraTudu() {
        initComponents();
        try
        {
            Scanner mathuratudu = new Scanner(new File("Mathura.txt"));
            String[] details = new String[6];
         
            while(mathuratudu.hasNext())
            {
                details[0]=mathuratudu.next();
                details[1]=mathuratudu.next();
                details[2]=mathuratudu.next();
                details[3]=mathuratudu.next();
                details[4]=mathuratudu.next();
                details[5]=mathuratudu.next();
                
            }
            Mproffession.setText(details[4]);
            MphoneNumber.setText(details[3]);
            Mplace.setText(details[5]);
        }catch(Exception e)
        {
            System.out.println("Sorry");
        }
        
        
    }
    public void setmyName(String iname)
    {
        MName.setText(iname);
        
    }
    public void setPhonenumber(String Iphonenumber)
    {
        MphoneNumber.setText(Iphonenumber);
    }
    public void setProffession(String Iphonenumber)
    {
        Mproffession.setText(Iphonenumber);
    }
    public void setPlace(String Iplace)
    {
        Mplace.setText(Iplace);
    }
    public void disablenec()
    {
        MaddFriend.setVisible(false);
        Msend.setVisible(false);
        Mtextarea.setVisible(false);
        
        Mmessagebutton.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MaddFriend = new javax.swing.JButton();
        Mproffession = new javax.swing.JLabel();
        MphoneNumber = new javax.swing.JLabel();
        Mplace = new javax.swing.JLabel();
        MBack = new javax.swing.JButton();
        Mmessagebutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mtextarea = new javax.swing.JTextArea();
        Msend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MName.setForeground(new java.awt.Color(0, 102, 51));
        MName.setText("Mathura Tudu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Proffession     --->>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Phone Number --->>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Place              --->>");

        MaddFriend.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MaddFriend.setForeground(new java.awt.Color(0, 0, 102));
        MaddFriend.setText("ADD FRIEND");
        MaddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaddFriendActionPerformed(evt);
            }
        });

        Mproffession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Mproffession.setForeground(new java.awt.Color(0, 102, 0));

        MphoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MphoneNumber.setForeground(new java.awt.Color(0, 102, 0));

        Mplace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Mplace.setForeground(new java.awt.Color(0, 102, 0));

        MBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MBack.setForeground(new java.awt.Color(0, 0, 153));
        MBack.setText("BACK");
        MBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBackActionPerformed(evt);
            }
        });

        Mmessagebutton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Mmessagebutton.setForeground(new java.awt.Color(0, 102, 0));
        Mmessagebutton.setText("LEAVE A MESSAGE");

        Mtextarea.setColumns(20);
        Mtextarea.setRows(5);
        jScrollPane1.setViewportView(Mtextarea);

        Msend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Msend.setForeground(new java.awt.Color(0, 102, 0));
        Msend.setText("SEND");
        Msend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mproffession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MphoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Mplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1032, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(MaddFriend)
                        .addGap(104, 104, 104)
                        .addComponent(MBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mmessagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Msend, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mproffession, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mmessagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Msend, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private static void writeToFile(String s,File F)throws IOException
    {
        FileWriter fr = new FileWriter(F,true);
        fr.write(s+" ");
        fr.close();
    }
    private void MaddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaddFriendActionPerformed
        // TODO add your handling code here:
        EnterLogin loginobj = new EnterLogin();
        String friends = loginobj.getthename();
        Scanner scan;
        friends = friends.concat("Friends.txt");
        try
        {
            File peoplefile = new File(friends);
            writeToFile(MName.getText(),peoplefile);
            
        }catch (Exception e)
        {
            System.out.println("Unable to create File");
        }
         JOptionPane.showMessageDialog(null,"You added Mathura Tudu","Adding Friend",JOptionPane.INFORMATION_MESSAGE);
         
        
    }//GEN-LAST:event_MaddFriendActionPerformed
    public void close(){
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }
    private void MBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBackActionPerformed
        // TODO add your handling code here:
        new SocioNet().setVisible(true);
        close();
        //obj.setVisible(false);
    }//GEN-LAST:event_MBackActionPerformed

    private void MsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsendActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Message Sent","Message Sending......",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MsendActionPerformed

    /**
     * @param args the command line arguments
     */
   /* static void setVisibility()
    {
        obj = new MathuraTudu();
        obj.setVisible(true);
    }*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathuraTudu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathuraTudu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathuraTudu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathuraTudu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new MathuraTudu().setVisible(true);
               // obj.setVisible(true);
               //setVisibility();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MBack;
    private javax.swing.JLabel MName;
    private javax.swing.JButton MaddFriend;
    private javax.swing.JLabel Mmessagebutton;
    private javax.swing.JLabel MphoneNumber;
    private javax.swing.JLabel Mplace;
    private javax.swing.JLabel Mproffession;
    private javax.swing.JButton Msend;
    private javax.swing.JTextArea Mtextarea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
